  
version: '3.3'
services:
  ecommerce:
    build: .    #soit lui indiquer le chemin du projet
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/ecommerceSite/  #./scheminApp avant les 2 points  si docker-compose n'est pas dans le même dossier
    ports:
      - 8009:8000
    env_file:
      - ./.env.dev  #renseigner le chemin du .env.dev
     
    #Adding new services for postgres configuration
    depends_on:
      - ecommerce-db
  ecommerce-db:   #<--- nom du service
    image: postgres:14-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ecommerce
      - POSTGRES_PASSWORD=ecommerce
      - POSTGRES_DB=ecommerce_dev
volumes:
  postgres_data:

 
