# Generated by Django 4.1.2 on 2022-11-03 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceApp.category', verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marked_price',
            field=models.PositiveBigIntegerField(verbose_name="Prix D'Achat"),
        ),
        migrations.AlterField(
            model_name='product',
            name='return_policy',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Politique de retour'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.PositiveBigIntegerField(verbose_name='Prix de Vente'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Nom Unique'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Garantie'),
        ),
    ]
