# Generated by Django 4.1.2 on 2022-11-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0004_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='adresse',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Adresse de residence'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=300, verbose_name='Nom Complet'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(max_length=30, verbose_name='Numéro de téléphone'),
        ),
    ]
